-- ORDER INTELLIGENCE - SNOWFLAKE PROJECT SETUP
-- Public portfolio version. Replace placeholders with values from your own environment.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS ORDER_INTELLIGENCE_DB;
CREATE SCHEMA IF NOT EXISTS ORDER_INTELLIGENCE_DB.RAW;

CREATE WAREHOUSE IF NOT EXISTS ORDER_INTELLIGENCE_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE DATABASE ORDER_INTELLIGENCE_DB;
USE SCHEMA RAW;
USE WAREHOUSE ORDER_INTELLIGENCE_WH;

-- Storage integration uses an IAM role rather than embedded AWS access keys.
-- Replace the placeholders below before running this script.
CREATE STORAGE INTEGRATION IF NOT EXISTS ORDER_INTELLIGENCE_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<SNOWFLAKE_S3_ROLE>'
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = (
    's3://<ORDER_INTELLIGENCE_BUCKET>/order-intelligence/landing/'
);

-- Use the values returned here to configure the AWS trust relationship.
DESC INTEGRATION ORDER_INTELLIGENCE_S3_INT;

CREATE FILE FORMAT IF NOT EXISTS ORDER_INTELLIGENCE_CSV_FF
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

CREATE FILE FORMAT IF NOT EXISTS ORDER_INTELLIGENCE_CSV_HEADER_FF
TYPE = CSV
FIELD_DELIMITER = ','
PARSE_HEADER = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

CREATE STAGE IF NOT EXISTS ORDER_INTELLIGENCE_S3_STAGE
URL = 's3://<ORDER_INTELLIGENCE_BUCKET>/order-intelligence/landing/'
STORAGE_INTEGRATION = ORDER_INTELLIGENCE_S3_INT
FILE_FORMAT = (FORMAT_NAME = 'ORDER_INTELLIGENCE_CSV_FF');

LIST @ORDER_INTELLIGENCE_S3_STAGE;

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS ORDER_INTELLIGENCE_LOADER;

GRANT USAGE ON WAREHOUSE ORDER_INTELLIGENCE_WH TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT USAGE ON DATABASE ORDER_INTELLIGENCE_DB TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT USAGE ON SCHEMA ORDER_INTELLIGENCE_DB.RAW TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT CREATE TABLE ON SCHEMA ORDER_INTELLIGENCE_DB.RAW TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA ORDER_INTELLIGENCE_DB.RAW TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA ORDER_INTELLIGENCE_DB.RAW TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT USAGE ON INTEGRATION ORDER_INTELLIGENCE_S3_INT TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT USAGE ON STAGE ORDER_INTELLIGENCE_DB.RAW.ORDER_INTELLIGENCE_S3_STAGE TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT USAGE ON FILE FORMAT ORDER_INTELLIGENCE_DB.RAW.ORDER_INTELLIGENCE_CSV_FF TO ROLE ORDER_INTELLIGENCE_LOADER;
GRANT USAGE ON FILE FORMAT ORDER_INTELLIGENCE_DB.RAW.ORDER_INTELLIGENCE_CSV_HEADER_FF TO ROLE ORDER_INTELLIGENCE_LOADER;

-- Grant the loader role to the Snowflake user or service principal used in your environment.
-- GRANT ROLE ORDER_INTELLIGENCE_LOADER TO USER <SNOWFLAKE_USER>;

SHOW GRANTS TO ROLE ORDER_INTELLIGENCE_LOADER;
SHOW FUTURE GRANTS TO ROLE ORDER_INTELLIGENCE_LOADER;

USE ROLE ORDER_INTELLIGENCE_LOADER;
USE DATABASE ORDER_INTELLIGENCE_DB;
USE SCHEMA RAW;
USE WAREHOUSE ORDER_INTELLIGENCE_WH;

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();
LIST @ORDER_INTELLIGENCE_S3_STAGE;
